on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: cci deploy
        id: build
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.10
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
